name: bionic_news
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  html: ^0.15.4
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.6 # ★★★ MODIFIED: 원본 기사 열기를 위해 사용합니다.
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
